namespace NodeJS {
	interface ProcessEnv {
		AUTH_COOKIE_NAME: string;
		AUTH_COOKIE_SIGNATURE_KEY_CURRENT: string;
		AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS: string;
		//
		FIREBASE_ADMIN_PRIVATE_KEY: string;
		FIREBASE_ADMIN_CLIENT_EMAIL: string;
		//
		NEXT_PUBLIC_FIREBASE_APP_ID: string;
		NEXT_PUBLIC_FIREBASE_API_KEY: string;
		NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
		NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
		NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
		NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
		//
		USE_SECURE_COOKIES: string;
	}
}
