import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function LayoutBeforeAuth({
	children,
}: Readonly<{ children: ReactNode }>) {
	return <main className="min-w-80 max-w-80 m-auto">{children}</main>;
}
