import { AuthProvider } from "@/components/auth";
import { Header } from "@/components/header";
import { getCurrentUser } from "@/features/auth";

import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type PrivateLayoutProps = Readonly<{
	children: ReactNode;
	// modal: ReactNode;
}>;

export default async function PrivateLayout({
	children,
	// modal,
}: PrivateLayoutProps) {
	const user = await getCurrentUser();

	return (
		<AuthProvider user={user}>
			<Header />
			<main>
				{children}
				{/* {modal} */}
			</main>
		</AuthProvider>
	);
}
